### ISSUE TITLE
upload

### ISSUE THREAD

**Issue by allyjweir** [allyjweir/wanders#11]
Need to integrate a smooth way of uploading a recording to the web Interface. One option is a webview which uses a submit page on the site designed to take the audio.3gp and the metadata.json.

Another option is to do it all properly and nicely.

Will do quick way and when a user account system is implemented correctly in the django app I will try to do it the nice way

**Comment by kaffo** [comment]
Remind me to sort out the form for the upload page so we can rip it straight from the app

**Comment by allyjweir** [comment]
Looked further into this but need a little coordination with the webapp folks. Will aim to have functioning by the end of today.

**Comment by allyjweir** [comment]
Using the insanely nice (and well documented) Android Async Http Client http://loopj.com/android-async-http/. I am sure we looked at it early on. 

Anyway I have implemented it and it just needs testing. As far as I understand it will send "audio.3gp" and "metadata.json" to "http://penida.dcs.gla.ac.uk/webapp/submit". It is Django's responsibility to handle the rest. Here's hoping!

**Comment by allyjweir** [comment]
Squares OkHTTP is the backup

**Comment by allyjweir** [comment]
After speaking with John I realised a painfully obvious mistake. Turns out I hadn't initialised a new  AsyncHttpResponseHandler(). I was actually directly referring to my httpUpload class instead of creating a handler to deal with it. Untested but thoroughly hoping it will do the trick. I suspect it will

**Comment by allyjweir** [comment]
Spent a little time on the django upload side of stuff. Changed the form to take the tar.gz as well. Also changed it from http://penida.dcs.gla.ac.uk/webapp/mobile_upload to http://penida.dcs.gla.ac.uk/webapp/upload. Need to reflect this in the code

**Comment by allyjweir** [comment]
reflected

**Comment by allyjweir** [comment]
It works, could do with some notifications to feed back to the user if upload was successful or not and offer a second chance at upload
